server:
  port: 8088  #tomcat??

spring: #springboot???
  datasource: #?????
    name: ershou
    #127.0.0.1??????ip?3306?mysql?????serverTimezone???????????mysql???????????
    #useSSL???????mysql???????SSL??
    url: jdbc:mysql://localhost:3306/ershou?useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&characterEncoding=utf8
    username: root  #???????root????
    password: lzy666


mybatis:  #mybatyis???
  mapper-locations: classpath:mapping/*.xml